### PR TITLE
added confusing favicon code to look over

### PR DESCRIPTION
**Pull request by karindalziel**

### CODE REVIEW

**Comment by techgique** [comment]
@karindalziel 
Could you try updating the favicon.ico file to one that has both 16x16 and 32x32 layers?

Curious if you think we should include smaller icon versions to prevent ugly scaling. I think this icon design will be okay, but others might require more finesse. Could add smaller icons on a case-by-case basis. I think this covers the ground floor though.

Also curious if you think the wide and large Windows tiles are worth adding. I can't imagine many people wanting to expand the tile size of a static tile for a web page like this.

**Comment by jduss4** [comment]
Do you know if there is anything particular about `public/apple-touch-icon.png` ?  It won't load in GitHub which strikes me as a bit odd, since it's a png

**Comment by jduss4** [comment]
I think the Rails code looks good, though I don't know enough about favicons and browserconfigs to really be of much use there.  So @karindalziel I'm giving this the Jessica stamp of approval, whenever you want to merge.

**Comment by techgique** [comment]
Yeah, images haven't been showing in GitHub for me either. I just scaled and renamed the images that were in Karin's earlier commit. Shouldn't be anything particularly weird about them?

**Comment by karindalziel** [comment]
I added the 16x16 and 32x32 favicon

**Pull request merged**
