### PR TITLE
Design fix

### PR DESCRIPTION
**Pull request by karindalziel**
Fixed paragraph indentation on copyright page and reorganized CSS. More CSS organization is needed, but it's a start!

### CODE REVIEW

**Comment by techgique** [comment]
All looks good to me. Grouping into sections like that helps a lot!

I went through and did some further tweaking how I like to organize CSS/Sass. It shouldn't change anything with how it actually applies other than the change to the text-shadow on h1 elements. It stayed the same number of rules in dev tools CSS editor post-Sass compilation, 1337 rules. 😃

**Comment by jduss4** [comment]
did you guys want me to look any of this over?

**Comment by techgique** [comment]
@karindalziel I remembered on my ride to work that there were a handful of border properties whose values were out of order. They have to be in the order `border: width, style, color` and quite a few had them out of order. I was already halfway through my last change and didn't separate them for their own commit. So it's possible we may see some borders where we previously hadn't.

**Comment by karindalziel** [comment]
@techgique I think as far as browsers are concerned the order doesn't matter (because browsers are used to interpreting sloppy css) so I've been needlessly sloppy - thanks for cleaning up, I'll be more consistent in the future!

**Pull request merged**
